baseURL = "http://example.org/"
languageCode = "en-us"
title = "PGE Stuff"
theme = "PaperMod"

[params]
  version = "1.0.6"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10